---
# Playbook will backup NXOS switch configurations

- name: "BACKUP NXOS DEVICE CONFIGURATION PLAYBOOK"
  hosts: nxos_switches

  tasks:
  - name: "CREATE BACKUPS DIRECTORY"
    file:
      path: "backups"
      state: "directory"
    changed_when: false
  
  - name: "BACKUP CONFIGURATION USING NXOS GALAXY MODULE"
    cisco.nxos.nxos_config:
      backup: "yes"
      backup_options:
        dir_path: "backups"
...