---
# Playbook to configure NXOS Leaf Switch using Cisco NXOS Galaxy modules

- name: "CONFIGURE NXOS LEAF SWITCHES USING GALAXY MODULES"
  hosts: nxos_switches

  tasks:
  - name: "CONFIGURE HOSTNAME"
    cisco.nxos.nxos_system:
      hostname: "{{ inventory_hostname }}"

  - name: "ENABLE FEATURES"
    cisco.nxos.nxos_feature:
      feature: "{{ item.feature }}"
      state: enabled
    with_items:
      - "{{ features }}"

  - name: "CONFIGURE ANYCAST GATEWAY"
    cisco.nxos.nxos_overlay_global:
      anycast_gateway_mac: "{{ anycast_gateway_mac }}"
    register: "ANYCAST_OUTPUT"

  - name: "CONFIGURE LOOPBACK INTERFACES"
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          description: "{{ item.description }}"
    with_items:
      - "{{ loopbacks }}"

  - name: "CONFIGURE LOOPBACK L3 INTERFACES"
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "{{ item.interface }}"
          ipv4:
          - address: "{{ item.ip_addr }}"
    with_items:
      - "{{ loopbacks }}"  
 
  - name: "CONFIGURE L3 INTERFACES"
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          description: "{{ item.description }}"
          mtu: "9216"
          mode: layer3
          enabled: true
    with_items:
      - "{{ l3_interfaces }}"

  - name: "CONFIGURE L3 IP UNNUMBERED"
    cisco.nxos.nxos_config:
      lines:
      - "medium p2p"
      - "ip unnumbered loopback0"
      parents: "interface {{ item.interface }}"
    with_items:
      - "{{ l3_interfaces }}"

  - name: "CONFIGURE OSPFV2"
    cisco.nxos.nxos_ospfv2:
      config:
        processes: 
        - process_id: "{{ ospf_process_id }}"
          router_id: "{{ ospf_router_id }}"
          areas:
          - area_id: "{{ ospf_area }}"
            authentication:
              set: no
          auto_cost:
            reference_bandwidth: 100
            unit: Gbps
          log_adjacency_changes:
            log: yes
  
  - name: "CONFIGURE OSPF L3 INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "ip ospf network point-to-point"
      - "ip router ospf {{ ospf_process_id }} area {{ ospf_area }}"
      parents: "interface {{item.interface }}"
    with_items:
      - "{{ l3_interfaces }}"
  
  - name: "CONFIGURE OSPF LOOPBACK INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "ip router ospf {{ ospf_process_id }} area {{ ospf_area }}"
      parents: "interface {{item.interface }}"
    with_items:
      - "{{ loopbacks }}"

  - name: "ENABLE NV OVERLAY EVPN"
    cisco.nxos.nxos_evpn_global:
      nv_overlay_evpn: true

  - name: "CONFIGURE BGP AND NEIGHBORS"
    cisco.nxos.nxos_bgp_global:
      config:
        as_number: "{{ bgp_asn }}"
        router_id: "{{ bgp_router_id }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            description: SPINE PEER
            update_source: "{{ item.update_source }}"
            remote_as: "{{ bgp_asn }}"
            log_neighbor_changes:
              set: yes
    with_items:
      - "{{ bgp_neighbors }}"
  
  - name: "CONFIGURE BGP L2VPN EVPN IPV4 UNICAST ADDRESS FAMILIES"
    cisco.nxos.nxos_bgp_neighbor_address_family:
      config:
        as_number: "{{ bgp_asn }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            address_family:
              - afi: l2vpn
                safi: evpn
              - afi: ipv4
                safi: unicast
                soft_reconfiguration_inbound:
                  always: yes
    with_items:
      - "{{ bgp_neighbors }}"
  
  - name: "CONFIGURE EXTENDED BGP COMMUNITIES"
    cisco.nxos.nxos_config:
      lines:
      - "send-community extended"
      parents: 
      - "router bgp {{ bgp_asn }}"
      - "neighbor {{ item.neighbor }}"
      - "address-family l2vpn evpn"
    with_items:
      - "{{ bgp_neighbors }}"

  - name: "CONFIGURE VLANS"
    cisco.nxos.nxos_vlans:
      config:
        - vlan_id: "{{ item.vlan_id }}"
          mapped_vni: "{{ item.vni_id }}"
          name: "{{ item.vlan_name }}"
    with_items:
      - "{{ vlans_l2vni }}"
      - "{{ vlans_l3vni }}"

  - name: "CONFIGURE HOST L2 TRUNK INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "description {{ item.description }}"
      - "switchport mode trunk"
      - "switchport trunk allowed vlan {{ item.allowed_vlans }}"
      - "spanning-tree port type edge trunk"
      - "spanning-tree bpduguard enable"
      parents: "interface {{ item.interface }}"
    with_items:
      - "{{ l2_interfaces }}"
    when: item.mode == "trunk"
    tags:
      - l2_int
  
  - name: "CONFIGURE HOST L2 ACCESS INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "description {{ item.description }}"
      - "switchport mode access"
      - "switchport access vlan {{ item.vlan }}"
      - "spanning-tree port type edge"
      - "spanning-tree bpduguard enable"
      parents: "interface {{ item.interface }}"
    with_items:
      - "{{ l2_interfaces }}"
    when: item.mode == "access"
    tags:
      - l2_int

  - name: "CONFIGURE TENANT VRFS"
    cisco.nxos.nxos_vrf:
      aggregate:
      - name: "{{ item.vrf }}"
        admin_state: up
        vni: "{{ item.vni_id }}"
        rd: "auto"
    with_items:
      - "{{ vrfs }}"
    tags:
      - vrfs
  
  - name: "CONFIGURE TENANT VRFS RT AND RD FOR EVPN"
    cisco.nxos.nxos_vrf_af:
      vrf: "{{ item.vrf }}"
      afi: "{{ item.afi }}"
      route_target_both_auto_evpn: yes
    with_items:
      - "{{ vrfs }}"
    tags:
      - vrfs_evpn

  - name: "CONFIGURE VXLAN VTEP NVE INTERFACE"
    cisco.nxos.nxos_interfaces:
      config:
        - name: nve1
          description: VTEP_INTERFACE
    tags:
      - nve

  - name: "CONFIGURE VXLAN VTEP NVE INTERFACE FOR EVPN CONTROL PLANE"
    cisco.nxos.nxos_vxlan_vtep:
      interface: nve1
      host_reachability: true 
      source_interface: loopback2
    tags:
      - nve
  
  - name: "CONFIGURE VXLAN VTEP NVE L2VNI MAPPINGS"
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.vni_id }}"
      ingress_replication: bgp
      suppress_arp: yes
    with_items: 
      - "{{ vlans_l2vni }}"
    tags:
      - l2_vni
  
  - name: "CONFIGURE VXLAN VTEP NVE L3VNI MAPPINGS"
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: nve1 
      vni: "{{ item.vni_id }}"
      assoc_vrf: yes 
    with_items: 
      - "{{ vlans_l3vni }}"
    tags:
      - l3_vni

  - name: "CONFIGURE L2 EVPN VNI"
    cisco.nxos.nxos_evpn_vni:
      vni: "{{ item.vni_id }}"
      route_distinguisher: auto
      route_target_import: auto
      route_target_export: auto
    with_items: "{{ vlans_l2vni }}"
    tags:
      - l2_evpn_vni

  - name: "CONFIGURE ROUTE MAP TO REDISTRIBUTE ROUTES INTO BGP"
    cisco.nxos.nxos_config:
      lines:
      - "match tag {{ item.vni_id }}"
      parents: "route-map {{ item.route_map }} permit 10"
    with_items:
      - "{{ vrfs }}"
    tags:
      - rm_tenants
 
  - name: "CONFIGURE TENANT VRFS UNDER BGP PROCESS"
    cisco.nxos.nxos_bgp_address_family:
      config:
        address_family:
          - afi: "{{ item.afi }}"
            safi: "{{ item.safi }}"
            vrf: "{{ item.vrf }}"
            redistribute:
              - protocol: direct
                route_map: "{{ item.route_map }}"
    with_items:
      - "{{ vrfs }}"
    tags:
      - bgp_vrfs    

  - name: "CONFIGURE SVI INTERFACES"
    cisco.nxos.nxos_interfaces:
      config:
      - name: "Vlan{{ item.vlan_id }}"
        description: "{{ item.vlan_name }}"
        enabled: true
    with_items:
      - "{{ vlans_l2vni }}"
      - "{{ vlans_l3vni }}"
    tags:
      - svi_int

  - name: "CONFIGURE SVI FOR TENANT VRFS"
    cisco.nxos.nxos_vrf_interface:
      vrf: "{{ item.vrf }}"
      interface: "Vlan{{ item.vlan_id }}"
      state: present
    with_items:
      - "{{ vlans_l2vni }}"
      - "{{ vlans_l3vni }}"
    tags:
      - int_vrfs
  
  - name: "CONFIGURE ANYCAST GATEWAY MODE FOR HOST SVI"
    cisco.nxos.nxos_interfaces:
      config:
      - name: "Vlan {{ item.vlan_id }}"
        fabric_forwarding_anycast_gateway: yes 
    with_items:
      - "{{ vlans_l2vni }}"
    tags:
      - any_cast_gw

  - name: "CONFIGURE SVI IP FORWARD VXLAN INTERFACES"
    cisco.nxos.nxos_interfaces:
      config:
      - name: "Vlan{{ item.vlan_id }}"
        description: "{{ item.vlan_name }}"
        ip_forward: yes
    with_items:
      - "{{ vlans_l3vni }}"
    tags:
      - svi_vxlan_int

  - name: "CONFIGURE SVI IP FOR HOST ROUTING"
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "Vlan{{ item.vlan_id }}"
          ipv4:
            - address: "{{ item.ip_addr }}"
              tag: "{{ item.tag }}"
          redirects: no
    with_items:
      - "{{ vlans_l2vni }}"
    tags:
      - svi_host_ip 
  
  # Apparent bug with galaxy interfaces module and SVIs are not set to enable
  - name: "ENABLE SVI INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "no shutdown"
      parents: "interface Vlan{{ item.vlan_id }}"
    with_items:
      - "{{ vlans_l2vni }}"
      - "{{ vlans_l3vni }}"
    tags:
      - svi_up
...