---
# Playbook to configure NXOS Spine Switch using Cisco NXOS Galaxy modules

- name: "CONFIGURE NXOS SPINES USING GALAXY MODULES"
  hosts: nxos_switches

  tasks:
  - name: "CONFIGURE HOSTNAME"
    cisco.nxos.nxos_system:
      hostname: "{{ inventory_hostname }}"

  - name: "ENABLE FEATURES"
    cisco.nxos.nxos_feature:
      feature: "{{ item.feature }}"
      state: enabled
    with_items:
      - "{{ features }}"

  - name: "CONFIGURE LOOPBACK INTERFACES"
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          description: "{{ item.description }}"
    with_items:
      - "{{ loopbacks }}"

  - name: "CONFIGURE LOOPBACK L3 INTERFACES"
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "{{ item.interface }}"
          ipv4:
          - address: "{{ item.ip_addr }}"
    with_items:
      - "{{ loopbacks }}"  
 
  - name: "CONFIGURE L3 INTERFACES"
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          description: "{{ item.description }}"
          mtu: "9216"
          mode: layer3
          enabled: true
    with_items:
      - "{{ l3_interfaces }}"

  - name: "CONFIGURE L3 IP UNNUMBERED"
    cisco.nxos.nxos_config:
      lines:
      - "medium p2p"
      - "ip unnumbered loopback0"
      parents: "interface {{ item.interface }}"
    with_items:
      - "{{ l3_interfaces }}"

  - name: "CONFIGURE OSPFV2"
    cisco.nxos.nxos_ospfv2:
      config:
        processes: 
        - process_id: "{{ ospf_process_id }}"
          router_id: "{{ ospf_router_id }}"
          areas:
          - area_id: "{{ ospf_area }}"
            authentication:
              set: no
          auto_cost:
            reference_bandwidth: 100
            unit: Gbps
          log_adjacency_changes:
            log: yes

  - name: "CONFIGURE OSPF L3 INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "ip ospf network point-to-point"
      - "ip router ospf {{ ospf_process_id }} area {{ ospf_area }}"
      parents: "interface {{item.interface }}"
    with_items:
      - "{{ l3_interfaces }}"
  
  - name: "CONFIGURE OSPF LOOPBACK INTERFACES"
    cisco.nxos.nxos_config:
      lines:
      - "ip router ospf {{ ospf_process_id }} area {{ ospf_area }}"
      parents: "interface {{item.interface }}"
    with_items:
      - "{{ loopbacks }}"

  - name: "ENABLE NV OVERLAY EVPN"
    cisco.nxos.nxos_evpn_global:
      nv_overlay_evpn: true

  - name: "CONFIGURE BGP AND NEIGHBORS"
    cisco.nxos.nxos_bgp_global:
      config:
        as_number: "{{ bgp_asn }}"
        router_id: "{{ bgp_router_id }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            description: LEAF PEER
            update_source: "{{ item.update_source }}"
            remote_as: "{{ bgp_asn }}"
            log_neighbor_changes:
              set: yes
    with_items:
      - "{{ bgp_neighbors }}"
  
  - name: "CONFIGURE BGP L2VPN EVPN ADDRESS FAMILY"
    cisco.nxos.nxos_bgp_neighbor_address_family:
      config:
        as_number: "{{ bgp_asn }}"
        neighbors:
          - neighbor_address: "{{ item.neighbor }}"
            address_family:
              - afi: l2vpn
                safi: evpn
                route_reflector_client: yes
    with_items:
      - "{{ bgp_neighbors }}"
  
  - name: "CONFIGURE EXTENDED BGP COMMUNITIES"
    cisco.nxos.nxos_config:
      lines:
      - "send-community extended"
      parents: 
      - "router bgp {{ bgp_asn }}"
      - "neighbor {{ item.neighbor }}"
      - "address-family l2vpn evpn"
    with_items:
      - "{{ bgp_neighbors }}"
...