---
# Host variable file for nxos-sw01

features:
  - feature: ospf
  - feature: bgp
  - feature: interface-vlan
  - feature: vn-segment-vlan-based
  - feature: nv overlay
  - feature: fabric forwarding

anycast_gateway_mac: aabb.cc01.1122

l3_interfaces:
  - interface: Ethernet1/1
    description: LINK_TO_SPINE1
  - interface: Ethernet1/2
    description: LINK_TO_SPINE2

l2_interfaces:
  - interface: Ethernet1/3
    description: LINK_TO_R1
    mode: trunk
    allowed_vlans: 100,200
  - interface: Ethernet1/4
    description: LINK_TO_R4
    mode: access
    vlan: "100"

loopbacks:
  - interface: loopback0
    description: UNDERLAY_LOOPBACK
    ip_addr: 172.16.1.3/32
  - interface: loopback1
    description: OVERLAY_LOOPBACK
    ip_addr: 172.17.1.3/32
  - interface: loopback2
    description: VTEP_LOOPBACK
    ip_addr: 172.18.1.3/32

ospf_process_id: UNDERLAY
ospf_router_id: "172.16.1.3"
ospf_area: "0.0.0.0"

bgp_asn: "65513"
bgp_router_id: "172.17.1.3"

address_families:
  - afi: l2vpn
    safi: evpn
  - afi: ipv4
    safi: unicast

bgp_neighbors:
  - remote_as: "65513"
    neighbor: "172.17.1.1"
    update_source: loopback1
  - remote_as: "65513"
    neighbor: "172.17.1.2"
    update_source: loopback1

vlans_l2vni:
  - vlan_id: 100
    vlan_name: Tenant-A_Accounting
    vni_id: 200100
    ip_addr: 10.100.100.1/24
    tag: 3100
    vrf: Tenant-A
  - vlan_id: 200
    vlan_name: Tenant-B_Sales
    vni_id: 200200
    ip_addr: 10.200.200.1/24
    tag: 3200
    vrf: Tenant-B

vlans_l3vni:
  - vlan_id: 3100
    vlan_name: VXLAN-Tenant-A_VLAN
    vni_id: 500100
    vrf: Tenant-A
  - vlan_id: 3200
    vlan_name: VXLAN-Tenant-B_VLAN 
    vni_id: 500200
    vrf: Tenant-B

vrfs:
  - vrf: Tenant-A
    vni_id: 500100
    afi: ipv4
    safi: unicast
    route_map: RM_TENANT_A_ROUTES
  - vrf: Tenant-B
    vni_id: 500200
    afi: ipv4
    safi: unicast
    route_map: RM_TENANT_B_ROUTES
...